#!/usr/bin/env node
/**
 * Stamp a unique build id into SW + a small TS module.
 * Runs before every production build so clients drop stale CSS/JS caches.
 */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const id =
  process.env.BUILD_ID ||
  `${Date.now().toString(36)}-${crypto.randomBytes(3).toString("hex")}`;

const cacheName = `sokratus-${id}`;

const swPath = path.join(root, "public", "sw.js");
let sw = fs.readFileSync(swPath, "utf8");
if (!/const CACHE_VERSION = /.test(sw)) {
  console.error("stamp-build: CACHE_VERSION not found in public/sw.js");
  process.exit(1);
}
sw = sw.replace(
  /const CACHE_VERSION = "[^"]*";/,
  `const CACHE_VERSION = "${cacheName}";`,
);
fs.writeFileSync(swPath, sw);

const tsPath = path.join(root, "src", "lib", "build-id.ts");
fs.writeFileSync(
  tsPath,
  `/** Auto-generated by scripts/stamp-build.mjs — do not edit. */\n` +
    `export const BUILD_ID = ${JSON.stringify(id)};\n` +
    `export const CACHE_NAME = ${JSON.stringify(cacheName)};\n`,
);

const jsonPath = path.join(root, "public", "build-id.json");
fs.writeFileSync(
  jsonPath,
  JSON.stringify({ id, cache: cacheName, at: new Date().toISOString() }),
);

console.log(`stamp-build: ${cacheName}`);
